"""renamed column merchant_name to description and deleted is_halal column.

Revision ID: 3f96800cb35e
Revises: d7e8bb32fb55
Create Date: 2026-02-22 15:35:55.931801

"""
from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f96800cb35e'
down_revision: Union[str, Sequence[str], None] = 'd7e8bb32fb55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=True))
    op.drop_column('transactions', 'is_halal_suspect')
    op.drop_column('transactions', 'merchant_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('merchant_name', sa.VARCHAR(length=150), autoincrement=False, nullable=True))
    op.add_column('transactions', sa.Column('is_halal_suspect', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('transactions', 'description')
    # ### end Alembic commands ###
