"""Add related_transaction_id to transaction

Revision ID: 922ea51fec00
Revises: 94d27d690a8f
Create Date: 2026-02-11 16:57:01.734214

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '922ea51fec00'
down_revision: Union[str, Sequence[str], None] = '94d27d690a8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('related_transaction_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'transactions', 'transactions', ['related_transaction_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_column('transactions', 'related_transaction_id')
    # ### end Alembic commands ###
