"""changed nullable to true of category field in transaction model.

Revision ID: 94d27d690a8f
Revises: 39eb5fc33b12
Create Date: 2026-02-09 23:19:31.257378

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94d27d690a8f'
down_revision: Union[str, Sequence[str], None] = '39eb5fc33b12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
