"""Initial migration with transaction, wallet, category models

Revision ID: d7b6d280f67c
Revises: dfcd3a0d43ee
Create Date: 2026-02-08 22:25:43.577473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7b6d280f67c'
down_revision: Union[str, Sequence[str], None] = 'dfcd3a0d43ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
