"""added new columns to category table

Revision ID: d7e8bb32fb55
Revises: fec27060eede
Create Date: 2026-02-22 03:01:33.867855

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd7e8bb32fb55'
down_revision: Union[str, Sequence[str], None] = 'fec27060eede'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    
    category_type = postgresql.ENUM('INCOME', 'EXPENSE', name='categorytype')
    category_type.create(op.get_bind())
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('type', sa.Enum('INCOME', 'EXPENSE', name='categorytype'), nullable=False))
    op.add_column('categories', sa.Column('user_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'categories', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'categories', type_='foreignkey')
    op.drop_column('categories', 'user_id')
    op.drop_column('categories', 'type')
    # ### end Alembic commands ###
