"""changing decimal fields properties

Revision ID: fec27060eede
Revises: 7480a6baeeb8
Create Date: 2026-02-22 02:35:16.548334

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fec27060eede'
down_revision: Union[str, Sequence[str], None] = '7480a6baeeb8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('currency_rates', 'rate',
               existing_type=sa.NUMERIC(precision=20, scale=6),
               nullable=False)
    op.alter_column('transactions', 'amount',
               existing_type=sa.NUMERIC(precision=20, scale=2),
               nullable=False)
    op.alter_column('wallets', 'balance',
               existing_type=sa.NUMERIC(precision=20, scale=2),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('wallets', 'balance',
               existing_type=sa.NUMERIC(precision=20, scale=2),
               nullable=True)
    op.alter_column('transactions', 'amount',
               existing_type=sa.NUMERIC(precision=20, scale=2),
               nullable=True)
    op.alter_column('currency_rates', 'rate',
               existing_type=sa.NUMERIC(precision=20, scale=6),
               nullable=True)
    # ### end Alembic commands ###
